apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - octolab-labs-default-deny.yaml
  - octolab-labs-allow-dns.yaml

# Common labels for all network policies
commonLabels:
  app.octolab.io/part-of: octolab
